# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimplyLaundry' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage'
  pod 'AFNetworking'

  # Registration with Google pod
  pod 'GoogleSignIn'

  # Registration with Facebook pod
  pod 'FacebookLogin'
  pod 'FBSDKCoreKit', '~> 4.38.0'
  pod 'FBSDKLoginKit', '~> 4.38.0'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  
  pod 'SideMenuController'

  pod 'IQKeyboardManagerSwift'

  pod 'DropDown'

  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

  pod 'VACalendar'
  # Pods for SimplyLaundry

end
